### PR TITLE
SOU-L1TSV+VR: implementation and unit test

### PR DESCRIPTION
**Pull request by atsuki-kuwata**
I added `examples/sou_l1tsv_vr.py` and unit test `bcd_l1tsv_vr_test.py` for SOU-L1TSV+VR,

In my environment, `examples/sou_l1tsv_vr.py` worked and the unit test passed.
Please confirm them.

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
Confirmed that all of the unit tests passed.

**Comment by HajimeKawahara** [comment]
`shirochan:~/jaxsot/examples(sou-l1tsv-vr)>python sou_l1tsv_vr.py`
Figure_1

**Review by HajimeKawahara — APPROVED** [review]

**Comment by 2ndmk2** [comment]
I confirm that I can run a unit test.

**Review by 2ndmk2 — COMMENTED** [review]
Code works.

**Pull request merged**
